### ISSUE TITLE
Request for Model Checkpoint

### ISSUE THREAD

**Issue by MalumaDev** [lmn-ning/ImageFusion#10]
Hi,

Thanks for sharing the MSI-DTrans code! I noticed there isn’t a pre-trained model checkpoint available. Could you please upload it? It would be really helpful for testing and experimentation without having to train from scratch.

Thanks in advance!

**Comment by lmn-ning** [comment]
Hello, due to a long time, I can not find the pre-training model. But the training and inference code in the repository is complete and can be easily run.
