### ISSUE TITLE
关于红外可见光融合

### ISSUE THREAD

**Issue by iZh7** [lmn-ning/ImageFusion#2]
请问您的这个能用来做红外可见光图像的融合吗

**Comment by lmn-ning** [comment]
据我所知，红外可见光图像的融合没有ground-truth的融合图像，无法直接用该模型，可以考虑基于该模型的改进。基于Diffusion的红外可见光图像可以参考论文《Dif-Fusion: Towards High Color Fidelity in Infrared and Visible Image Fusion with Diffusion Models》
