### ISSUE TITLE
请问你们的实验是在单张3090上训练的吗？训练时间大概多长？ 谢谢。

### ISSUE THREAD

**Issue by shiyu5feng** [lmn-ning/ImageFusion#3]

**Comment by lmn-ning** [comment]
是的，可以在单卡3090/4090上训练。时间过去太久，具体训练耗时我记不清楚了。单卡3090训练1-2周，4090训练5天左右。

**Comment by shiyu5feng** [comment]
> 是的，可以在单卡3090/4090上训练。时间过去太久，具体训练耗时我记不清楚了。单卡3090训练1-2周，4090训练5天左右。

好的，谢谢
