### ISSUE TITLE
question，thanks

### ISSUE THREAD

**Issue by Zhangwp2420** [lmn-ning/ImageFusion#4]
请问 多曝光可以适用吗，我目前不知道该怎么弄带ground truth的数据集

**Comment by lmn-ning** [comment]
据我所知，红外可见光图像的融合没有ground-truth的融合图像，无法直接用该模型，可以考虑基于该模型的改进。基于Diffusion的红外可见光图像可以参考论文《Dif-Fusion: Towards High Color Fidelity in Infrared and Visible Image Fusion with Diffusion Models》
