### ISSUE TITLE
Noisy image fusion

### ISSUE THREAD

**Issue by puduliu** [lmn-ning/ImageFusion#9]
Thank you for your paper. I have a question, why can the PSNR of the image fusion with added noise reach 70+? I used the IFCNN pre-trained model to add Gaussian noise with sigma =  0.1 to two images, and the PSNR was only 20+, not70+.

I hope to get your answer，thank you.

**Comment by lmn-ning** [comment]
According to section 4.4.2, the paper retrains IFCNN and SDNet using the noisy image dataset instead of reasoning directly using the pre-trained models.
